version: '3.8'

services:
  app:
    # Use pre-built image from Docker Hub (no building on server)
    image: mnbactabio/bacta-apps:latest
    container_name: app
    expose:
      - "8000"
    env_file:
      - ../.env
    environment:
      - GUNICORN_CMD_ARGS=--workers=3 --threads=2 --bind=0.0.0.0:8000 --timeout=60 --keep-alive=5 --access-logfile=- --error-logfile=-
      # If behind a proxy, uncomment:
      # - GUNICORN_CMD_ARGS=--workers=3 --threads=2 --bind=0.0.0.0:8000 --proxy-allow-from="*" --forwarded-allow-ips="*"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request;urllib.request.urlopen('http://localhost:8000/healthz')"]
      interval: 30s
      timeout: 3s
      retries: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  nginx:
    image: nginx:stable
    container_name: nginx
    depends_on:
      - app
    ports:
      - "80:80"
      # - "443:443"   # if terminating TLS in Nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped

  benchling-helper:
    image: mnbactabio/benchling:latest
    container_name: benchling-helper
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

